export {default as HeaderMain} from './HeaderMain'
export {default as HotbarMain, HotbarMainProps} from './HotbarMain'
export {default as FooterMain} from './FooterMain'
export {default as LoginMain} from './LoginMain'
export {default as TabsMain, TabsMainProps} from './TabsMain'
