export {default as HeaderMain, HeaderMainProps} from './HeaderMain'
export {default as HotbarMain, HotbarMainProps} from './HotbarMain'
export {default as FooterMain} from './FooterMain'
export {default as LoginMain, LoginMainProps} from './LoginMain'
export {default as TabsMain, TabsMainProps} from './TabsMain'
